### ISSUE TITLE
Version without verbose debugging output

### ISSUE THREAD

**Issue by bastibe** [adfernandes/precompiled-portaudio-windows#1]
Thank you so much for providing compiled portaudio DLLs!

I know from experience how ... hard it can be to compile portaudio with all its backends.

Here is a feature request though: 
Could you compile an additional version without `PA_ENABLE_DEBUG_OUTPUT`? I am using your libraries for the Windows versions of my [PortAudio bindings for Python](https://github.com/bastibe/PySoundCard) and the debug output is rather annoying while using the library on the command line.

**Comment by adfernandes** [comment]
No problem; I had thought that the debug output was only enabled on the debug builds... I'll double-check and fix it on my next build, but that might not be for a couple of weeks.

**Comment by bastibe** [comment]
Thank you very much!

**Comment by adfernandes** [comment]
Wow. Over a year. Sorry.

Unfortunately, I have bad news; we finally dusted off our Windows Visual Studio VM, and ... we cannot compile PortAudio r1934. There were ASIO issues (which seemed to go away with the 2.3 ASIO SDK), but we also had library build issues due to changes in the MS SDK.

So, unfortunately, we won't be supporting PortAudio builds on Windows from now on. Sorry.
