### ISSUE TITLE
How about the latest version?

### ISSUE THREAD

**Issue by pauldotknopf** [adfernandes/precompiled-portaudio-windows#2]
Can you build us the "January 30, 2014, SVN rev 1919" version?

**Comment by adfernandes** [comment]
Unfortunately, I have bad news; we finally dusted off our Windows Visual Studio VM, and ... we cannot compile PortAudio r1934. There were ASIO issues (which seemed to go away with the 2.3 ASIO SDK), but we also had library build issues due to changes in the MS SDK.

So, unfortunately, we won't be supporting PortAudio builds on Windows from now on. Sorry.

**Comment by pauldotknopf** [comment]
Thanks. I winded up build it myself.

https://github.com/theonlylawislove/PortAudio/commits/master
